[package]
name = "typst-to-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
typst = {git = "https://github.com/typst/typst.git", tag = "v0.9.0"}
wasm-bindgen = { version = "0.2", features = ["serde"] }
serde_json = "1.0"

[lib]
path = "src/rust/lib.rs"
crate-type = ["cdylib", "rlib"]
